# Site Settings
title: "Andrei // Notes"
description: "Human thoughts on a technical world."

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Author Sidebar
author:
  name   : "Andrei"
  avatar : "https://andrei7506238.github.io/soft-dev-portofolio/images/showcase/profile.jpeg" 
  bio    : "Mobile Software Developer."
  location: "Brașov, Romania"
  links:
    - label: "Back to Portfolio"
      icon: "fas fa-fw fa-arrow-left"
      url: "https://andrei7506238.github.io/soft-dev-portofolio/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andrei7506238"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrei-robert-popa/"

# Simplified Defaults
    - scope:
      path: ""
      type: posts
    - values:
      layout: single
      author_profile: true
      read_time: true # Important: shows you value the reader's time
      share: false    # Keep it humble; no need for 'Viral' buttons
      related: true

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-feed